CREATE TABLE questions
(
   id BIGSERIAL PRIMARY KEY,
   user_id BIGSERIAL NOT NULL,
   text VARCHAR(250) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_user
      FOREIGN KEY(user_id)
	  REFERENCES users(id)
);