CREATE TABLE options
(
   id BIGSERIAL PRIMARY KEY,
   question_id BIGSERIAL NOT NULL,
   text VARCHAR(250) NOT NULL UNIQUE,
   active BOOLEAN NOT NULL DEFAULT TRUE,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_question
      FOREIGN KEY(question_id)
	  REFERENCES questions(id)
);